services:
  song-lib:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: song-lib
    restart: always
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:alpine
    container_name: song-lib-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - song_lib_postgres_volume:/var/lib/postgresql/data

volumes:
  song_lib_postgres_volume:
